### ISSUE TITLE
无法使用HPatch还原文件

### ISSUE THREAD

**Issue by huangmingfeisss** [wangchz13/MiniHdiffPatch#1]
用HDiff生成差分.bin文件，发现差分.bin文件头部都有82 00 82 00数据，
![image](https://github.com/wangchz13/MiniHdiffPatch/assets/70952702/ed02dbd2-73bd-410f-b376-8527e777a867)

使用HPatch工程进行还原，hpatch_unpackUIntWithTag读取差分.bin文件，unpackUIntTo(&newsize, &patchData_temp); 会导致返回的src_code为0
![image](https://github.com/wangchz13/MiniHdiffPatch/assets/70952702/a24d8662-a2d3-4ec7-9e15-9fc58d21bee6)
![image](https://github.com/wangchz13/MiniHdiffPatch/assets/70952702/fcc936d4-7411-4591-8fcc-17b1d1af3ee2)

再次unpackUIntTo(&oldsize, &patchData_temp);会出错
![image](https://github.com/wangchz13/MiniHdiffPatch/assets/70952702/6a8370bc-b7f4-4cc3-8a6c-0686f4dc3ccd)

无法使用HPatch还原文件
![image](https://github.com/wangchz13/MiniHdiffPatch/assets/70952702/c7c1ffe3-2362-4fa1-84c4-7820f5835987)

**Comment by wangchz13** [comment]
看样子是长度编解码出问题了，最好提供一下new.bin old.bin patch.bin

**Comment by huangmingfeisss** [comment]
可以了，这个问题是，我用QT调试，不用main命令传递参数信息，用了局部变量做实参，导致指针返回值为空。调试的时候用全局变量做实参就可以了。
